[tool.poetry]
name = "bootupscreen-customizer"
version = "0.1.0"
description = "A simple tool to customize your bootupscreen on unix-systems using plymouth"
authors = ["protogia"]

[tool.poetry.dependencies]
python = "^3.7"
opencv-python = "^4.5.3"
rich-argparse = "^1.4.0"
inquirerPy = "^0.3.4 "

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
